version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - ${RMQ_PORT}:5672
      - ${RMQW_PORT}:15672
    environment:
      - RABBITMQ_DEFAULT_USER=${RMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RMQ_PASSWORD}

volumes:
  redis_data:
